name: Access ID Workflow
on:
  push:
    branches:
      - main
jobs:
  print-access-id:
    runs-on: ubuntu-latest
    env:
      ACCESS_ID: ${{ vars.ACCESS_ID}}
      
    steps:
      - name: Print Access ID
        run: echo "The ACCESS_ID is $ACCESS_ID"
