name: Deploy to Staging
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        type: string
        required: true
      environment:
        required: true
        default: "staging"
        type: choice
        options:
          - development
          - staging
          - production
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo "Deploying version ${{ github.event.inputs.version }} to staging..."
          #  Add your deployment commands here
