name: Access ID Workflow
on:
  push:
    branches:
      - main
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.SECRET }}
      
    steps:
      - name: SECRET
        run: echo "The SECRET is $SECRET"
